import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
const EpilogueFont = Epilogue({
  variable: "--font-EpilogueFont",
  subsets: ["latin"],
});

const myFont = localFont({
  src: [
    {
      path: "../public/font/clash-display-font/ClashDisplay-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/font/clash-display-font/ClashDisplay-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-my-local",
});

export const metadata: Metadata = {
  title: "QuickHire",
  description: "Generated by QuickHire",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${EpilogueFont.variable} ${myFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
